---
title: "In-class Prediction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
if(!require("EBImage")){
  source("https://bioconductor.org/biocLite.R")
  biocLite("EBImage")
}
if(!require("R.matlab")){
  install.packages("R.matlab")
}
if(!require("readxl")){
  install.packages("readxl")
}
if(!require("dplyr")){
  install.packages("dplyr")
}
if(!require("readxl")){
  install.packages("readxl")
}
if(!require("ggplot2")){
  install.packages("ggplot2")
}
if(!require("caret")){
  install.packages("caret")
}
if(!require("gbm")){
  install.packages("gbm")
}
if(!require("e1071")){
  install.packages("e1071")
}
if(!require("geometry")){
  install.packages("geometry")
}
if(!require("mlogit")){
  install.packages("mlogit")
}
if(!require("tidyverse")){
  install.packages("tidyverse")
}
if(!require("xgboost")){
  install.packages("xgboost")
}

library(R.matlab)
library(readxl)
library(dplyr)
library(EBImage)
library(ggplot2)
library(caret)
library(gbm)
library(e1071)
library(geometry)
library(mlogit)
library(tidyverse)
library(xgboost)  
```

## Step 0: Build train model

```{r}
run.build = FALSE
run.save = FALSE
```

```{r}
if(run.build){
  set.seed(1)
  setwd("C:/course/5243 Applied Data Science/Project/Spring2020-Project3-group8/doc")
  
  train_dir <- "../data/train_set/" # This will be modified for different data sets.
  train_image_dir <- paste(train_dir, "images/", sep="")
  train_pt_dir <- paste(train_dir,  "points/", sep="")
  train_label_path <- paste(train_dir, "label.csv", sep="") 
  
  info <- read.csv(train_label_path)
  n <- nrow(info)
  train_idx <- sample(1:n, n, replace = F)
}
```

```{r}
if(run.build){
  source("../lib/feature.R")
  load("../output/fiducial_pt_list.RData")
  load("../output/all_points.RData")
  
  tm_feature_train_inclass <- system.time(dat_all <- feature(fiducial_pt_list, train_idx, image_file = "../data/train_set/images/", all_points, colorfeature = TRUE))
  save(dat_all, file="../output/feature_all.RData")
}
```

```{r}
if(run.build){
  source("../lib/train_SVM.R")
  load("../output/feature_all.RData")
  
  svm_result_all = svm_train(dat_all, kernel = 'poly', degree = 1, gamma = 0.008)
  svm_model_all = svm_result_all[[1]]
  tm.svm.train_all = svm_result_all[[2]]
  save(svm_model_all, file="../output/svm_model_all.RData")
}
```

```{r}
if(run.build){
  source("../lib/feature_baseline.R")
  load("../output/fiducial_pt_list.RData")
  tm_feature_train_inclass_baseline <- system.time(dat_all_baseline <- feature_baseline(fiducial_pt_list, train_idx))
  save(dat_all_baseline, file="../output/feature_all_baseline.RData")
}
```

```{r}
if(run.build){
  source("../lib/train_gbm.R")
  load("../output/feature_all_baseline.RData")
  
  baseline_result_all = gbm_train(dat_all_baseline, n.trees = 200, bag.fraction = 0.8, shrinkage = 0.1, cv.folds = 3)
  baseline_all_model = baseline_result_all[[1]]
  tm.all_baseline = baseline_result_all[[2]]
  save(baseline_all_model, file="../output/baseline_all_model.RData")
}
```

## Step 1: Set inclass work directories

```{r}
set.seed(1)
setwd("C:/course/5243 Applied Data Science/Project/Spring2020-Project3-group8/doc")
# here replace it with your own path or manually set it in RStudio to where this rmd file is located. 
# use relative path for reproducibility
```

```{r}
test_dir <- "../data/test_set_predict/" 
test_image_dir <- paste(test_dir, "images/", sep="")
test_pt_dir <- paste(test_dir,  "points/", sep="")
test_label_path <- paste(test_dir, "labels_prediction.csv", sep="") 
```

## Step 2: Data reading and preprocessing

```{r}
info <- read.csv(test_label_path)
n <- nrow(info)
test_idx <- 1:n
```

```{r read fiducial points}
#function to read fiducial points
#input: index
#output: matrix of fiducial points corresponding to the index
n_files <- length(list.files(test_image_dir))
readMat.matrix <- function(index){
  return(round(readMat(paste0(test_pt_dir, sprintf("%04d", index), ".mat"))[[1]],0))
}
  
#load fiducial points
fiducial_pt_list_inclass <- lapply(1:n_files, readMat.matrix)
save(fiducial_pt_list_inclass, file="../output/fiducial_pt_list_inclass.RData")
```

```{r}
source("../lib/change_images.R")
load("../output/fiducial_pt_list_inclass.RData")
  
single = c(35,36,37,38,44,52,56,59,62)
double = data.frame(
  x1 = c(1,2,3,4,5,6,7,8,9,19,20,21,22,23,24,25,26,39,40,41,42,43,50,51,57,58,63),
  x2 = c(10,15,14,13,12,11,18,17,16,31,30,29,28,27,34,33,32,49,48,47,46,45,54,53,55,60,61))
indices = 1:n
  
tm.run.all_points_inclass = system.time(all_points_inclass <- change_points(indices, test_dir, fiducial_pt_list_inclass, single, double))
  
all_points_inclass = map(all_points_inclass, as.matrix)
  
save(all_points_inclass, file = "../output/all_points_inclass.RData")
```

## Step 3: Feature extraction

For baseline model

```{r}
source("../lib/feature_baseline.R")
load("../output/fiducial_pt_list_inclass.RData")
tm_feature_test_inclass_baseline <- system.time(dat_inclass_baseline <- feature_baseline(fiducial_pt_list_inclass, test_idx, inclass = TRUE))
save(dat_inclass_baseline, file="../output/feature_inclass_baseline.RData")
```

For improved model

```{r}
source("../lib/feature.R")
load("../output/all_points_inclass.RData")

tm_feature_test_inclass <- system.time(dat_inclass <- feature(fiducial_pt_list_inclass, test_idx, image_file = "../data/test_set_predict/images/", all_points_inclass, colorfeature = TRUE, inclass = TRUE))
save(dat_inclass, file="../output/feature_inclass.RData")
```

## Step 4: Predict in-class data.

For baseline model

```{r}
source("../lib/test_GBM.R")
load("../output/baseline_all_model.RData")
load("../output/feature_inclass_baseline.RData")

baseline_result_test_inclass = gbm_test(baseline_all_model, dat_inclass_baseline)
baseline_pred_inclass = baseline_result_test_inclass[[1]]
tm.baseline.test_inclass = baseline_result_test_inclass[[2]]
baseline_pred_class_inclass = apply(baseline_pred_inclass, 1, which.max)
```

For improved model

```{r}
source("../lib/test_SVM.R")
load("../output/svm_model_all.RData")
load("../output/feature_inclass.RData")

svm_result_test_inclass = svm_test(svm_model_all, dat_inclass)
svm_pred_class_inclass = svm_result_test_inclass[[1]]
tm.svm.test_inclass = svm_result_test_inclass[[2]]
```

## Step 5: Conclusion

For baseline model

```{r}
#confusionMatrix(factor(baseline_pred_class_inclass), dat_inclass_baseline$emotion_idx)
```

```{r}
#baseline_accuracy_test_inclass = mean(dat_inclass_baseline$emotion_idx == baseline_pred_class_inclass)
#print(paste0("The accuracy for baseline model is: ", baseline_accuracy_test_inclass))
```

```{r}
time_baseline = signif(tm_feature_test_inclass_baseline[3] + tm.baseline.test_inclass[3], 5)
print(paste0("The test time for baseline model is ", time_baseline, ' s'))
```

For improved model

```{r}
#confusionMatrix(factor(svm_pred_class_inclass), dat_inclass$emotion_idx)
```

```{r}
#svm_accuracy_test_inclass = mean(dat_inclass$emotion_idx == svm_pred_class_inclass)
#print(paste0("The accuracy for svm model is: ", svm_accuracy_test_inclass))
```

```{r}
time = signif(tm_feature_test_inclass[3] + tm.svm.test_inclass[3], 5)
print(paste0("The test time for improved model is ", time, ' s'))
```

## Step 6: Save result

```{r}
if(run.save){
  save_result = data.frame(Index = test_idx, Baseline = baseline_pred_class_inclass, Advanced = svm_pred_class_inclass)
  write.csv(save_result, file = "../data/test_set_predict/labels_prediction.csv",  row.names = T)
}
```



