---
title: "inv change point"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

A test on inv-change_image function

```{r}
library(EBImage)
library(tidyverse)
source("../lib/change_images.R")
info <- read.csv("../data/train_set/label.csv")
load("../output/all_points.Rdata")
load("../output/fiducial_pt_list.RData")
```

```{r}
index = 2497
points = fiducial_pt_list[[index]]
endpoints = all_points[[index]]
```

```{r}
plot(points[,1], -points[,2], col = 'red', cex = 1, pch = 16, xlim = c(0,1000), ylim = c(-750,0))
points(endpoints[,1], -endpoints[,2], col = 'blue', cex = 1, pch = 16)
```

```{r}
single = c(35,36,37,38,44,52,56,59,62)
double = data.frame(x1 = c(1,2,3,4,5,6,7,8,9,19,20,21,22,23,24,25,26,39,40,41,42,43,50,51,57,58,63),
                    x2 = c(10,15,14,13,12,11,18,17,16,31,30,29,28,27,34,33,32,49,48,47,46,45,54,53,55,60,61))
fixdist = -170
center_x = 500
center_y = 375
```

```{r}
pos_single = data.frame(x = points[single,1], y = points[single,2])
pos_double=data.frame(x=0.5*points[double[,1],1]+0.5*points[double[,2],1],
                        y=0.5*points[double[,1],2]+0.5*points[double[,2],2])
pos=rbind(pos_single,pos_double)
```

```{r}
angle = cal_angle(pos)
points_rotation = cal_rotation(points, angle)
  
my_fixdist = cal_fixdist(points_rotation)
rate = fixdist/my_fixdist
points_zoom = cal_zoom(points_rotation, rate)
  
points_translate = cal_translate(points_zoom, center_x, center_y)
```

```{r}
mean(endpoints - points_translate < 1e-10)
```

```{r}
endpoints_zoom = cal_translate(endpoints, points_zoom[37,1], points_zoom[37,2])
endpoints_rotation = cal_zoom(endpoints_zoom, 1/rate)
endpoints_end = cal_rotation(endpoints_rotation, -angle, center_x = 750*sin(angle), center_y = 0, move_x = -750*sin(angle), move_y = 0)
```

```{r}
r1 = 2
r2 = 9
x = 4
y = 7
a = cal_rotation(points,angle, r1,r2,x,y)
a = cal_rotation(a, -angle, r1+x,r2+y, -x,-y)
sum(a-points)
```

```{r}
source("../lib/inv_change_images.R")
sum(inv_change_points(points, endpoints) - points)
```

```{r}
a = data.frame(x = c(300, 520, 100, 700, 900), y = c(300, 520, 100, 600, 240))
b = inv_change_points(points, a)
plot(points[,1], -points[,2], col = 'red', cex = 0.1, pch = 16, xlim = c(0,1000), ylim = c(-750,0))
points(endpoints[,1], -endpoints[,2], col = 'blue', cex = 0.1, pch = 16)
points(a[,1], -a[,2], col = 'blue', cex = 1, pch = 3)
points(b[,1], -b[,2], col = 'red', cex = 1, pch = 3)
```













