---
title: "image rotation all"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(EBImage)
library(tidyverse)
```

```{r}
single = c(35,36,37,38,44,52,56,59,62)
double = data.frame(x1 = c(1,2,3,4,5,6,7,8,9,19,20,21,22,23,24,25,26,39,40,41,42,43,50,51,57,58,63),
                    x2 = c(10,15,14,13,12,11,18,17,16,31,30,29,28,27,34,33,32,49,48,47,46,45,54,53,55,60,61))
```

```{r}
cal_angle = function(pos){
  model = lm(x ~ y, data = pos)
  summary(model)
  angle = atan(model$coefficients[2])
  
  return(angle)
}

cal_rotation = function(points, angle){
  points_rotation = data.frame(x = NULL, y = NULL)
  for(i in 1:78){
    x = points[i,1] - 0
    y = points[i,2] - 0
    alpha = atan(y/x)
    d = sqrt(x^2+y^2)
    newx = d*cos(alpha + angle) + 0 + 750*sin(angle)
    newy = d*sin(alpha + angle) + 0
    
    points_rotation = rbind(points_rotation, data.frame(x = newx, y = newy))
  }
  
  return(points_rotation)
}

cal_translate = function(points, center_x = 500, center_y = 375){
  points_translate = data.frame(x = NULL, y = NULL)
  for(i in 1:78){
    newx = points[i,1] + (center_x - points[37,1])
    newy = points[i,2] + (center_y - points[37,2])
    points_translate = rbind(points_translate, data.frame(x = newx, y = newy))
  }
  
  return(points_translate)
}

move_images = function(points, img, center_x = 500, center_y = 375){
  pos = data.frame(x = points[single,1], y = points[single,2])
  for(i in 1:nrow(double)){
    pos = rbind(pos, data.frame(x = (points[double[i,1],1]+points[double[i,2],1])/2, 
                                y = (points[double[i,1],2]+points[double[i,2],2])/2))
  }
  
  angle = cal_angle(pos)
  points_rotation = cal_rotation(points, angle)
  points_translate = cal_translate(points_rotation, center_x, center_y)
  
  img_rotate = rotate(img, angle/2/pi*360)
  img_translate = translate(img_rotate, c(center_x-points_rotation[37,1],
                                          center_y-points_rotation[37,2]))

  return(list(points_translate, img_translate))
}

change_image = function(indices = c(1,2)){
  image.path_sub = map(indices, ~paste0(train_image_dir, sprintf("%04d", .x), ".jpg"))
  image.list_sub = map(image.path_sub, ~EBImage::readImage(.x))
  img = map(image.list_sub, ~Image(.x, colormode = 'Color'))
  
  fiducial_pt_list_sub = fiducial_pt_list[indices]
  points = map(fiducial_pt_list_sub, ~data.frame(x = .x[1:78,1], y = .x[1:78,2]))
  result_move = map(1:length(points), ~move_images(points[[.x]], img[[.x]]))
  
  return(result_move)
}

```

```{r}
indices = 1:3
result_move = change_image(indices)
new_points = map(result_move, ~.x[[1]])
new_img = map(result_move, ~.x[[2]])
```

```{r}
display(new_img[[3]], method = 'raster')
points(new_points[[3]]$x, new_points[[3]]$y, col = 'blue', cex = 1, pch = 16)
```

```{r}
begin = Sys.time()
indices = 1:25
result_move = change_image(indices)
new_points = map(result_move, ~.x[[1]])
new_img = map(result_move, ~.x[[2]])
end = Sys.time()
```

```{r}
(end-begin)*100
```

```{r}
all_points = NULL
for(i in 1:2){
  indices = 1:25 + (i-1)*25
  result_move = change_image(indices)
  new_points = map(result_move, ~.x[[1]])
  new_img = map(result_move, ~.x[[2]])
  all_points = c(all_points, new_points)
  
}
```








```{r}
# Only points no images
move_points = function(points, center_x = 500, center_y = 375){
  pos = data.frame(x = points[single,1], y = points[single,2])
  for(i in 1:nrow(double)){
    pos = rbind(pos, data.frame(x = (points[double[i,1],1]+points[double[i,2],1])/2, 
                                y = (points[double[i,1],2]+points[double[i,2],2])/2))
  }
  
  angle = cal_angle(pos)
  points_rotation = cal_rotation(points, angle)
  points_translate = cal_translate(points_rotation, center_x, center_y)

  return(points_translate)
}

change_points = function(indices = c(1,2)){
  fiducial_pt_list_sub = fiducial_pt_list[indices]
  points = map(fiducial_pt_list_sub, ~data.frame(x = .x[1:78,1], y = .x[1:78,2]))
  result_move = map(1:length(points), ~move_points(points[[.x]]))
  
  return(result_move)
}
```

```{r}
begin2 = Sys.time()
indices = 1:25
new_points = change_points(indices)
end2 = Sys.time()
```

```{r}
(end2-begin2)*100
```

```{r}
begin3 = Sys.time()
indices = 1:2500
all_points = change_points(indices)
end3 = Sys.time()
all_points = map(all_points, as.matrix)
```

```{r}
end3-begin3
```

```{r}
save(all_points, file="../output/all_points.RData")
```




