---
title: "stats"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
info <- read.csv("../data/train_set/label.csv")
load("../output/all_points.RData")
load("../output/ave_points.RData")

my_theme = theme_light() + 
  theme(plot.title = element_text(hjust = 0.5), 
        plot.subtitle = element_text(hjust = 0.5))
```

```{r}
t1 = NULL
for(i in 1:22){
  t = tibble(index = 1:78, x = ave_points[[i]][,1], y = ave_points[[i]][,2], label = i)
  t1 = rbind(t1, t)
}

t2 = t1 %>% 
  arrange(index, x) %>% 
  group_by(index) %>% 
  summarize(xmin = x[1], xmax = x[22], ymin = y[1], ymax = y[22], labelmax = label[1], labelmin = label[22]) %>%
  pivot_longer(-index) %>% 
  mutate(name1 = substr(name, 1, nchar(name)-3), name2 = substr(name, nchar(name)-2, nchar(name))) %>% 
  select(-name) %>% 
  pivot_wider(names_from = 'name1', values_from = 'value') %>% 
  mutate(label = with(info, emotion_cat %>% unique())[label]) %>% 
  group_by(index) %>%
  mutate(x = x - x[1])

t3 = t1 %>% 
  arrange(index, y) %>% 
  group_by(index) %>% 
  summarize(xmin = x[1], xmax = x[22], ymin = y[1], ymax = y[22], labelmax = label[1], labelmin = label[22]) %>%
  pivot_longer(-index) %>% 
  mutate(name1 = substr(name, 1, nchar(name)-3), name2 = substr(name, nchar(name)-2, nchar(name))) %>% 
  select(-name) %>% 
  pivot_wider(names_from = 'name1', values_from = 'value') %>% 
  mutate(label = with(info, emotion_cat %>% unique())[label]) %>% 
  group_by(index) %>%
  mutate(y = y - y[1])

```

```{r}
g1 = t2 %>%
  ggplot(mapping = aes(x = index, y = x, color = label)) +
  geom_point() + 
  my_theme
g1
```

```{r}
g2 = t3 %>%
  ggplot(mapping = aes(x = index, y = y, color = label)) +
  geom_point() + 
  my_theme
g2
```

```{r}
t4 = NULL
for(i in 1:2500){
  t = tibble(index = 1:78, x = all_points[[i]][,1], y = all_points[[i]][,2], points = i)
  t4= rbind(t4, t)
}
t4 = t4 %>% 
  mutate(label = info$emotion_cat[points])
```

```{r}
t5 = t4 %>% 
  group_by(label, index) %>% 
  summarize(varx = var(x), vary = var(y))
```

```{r}
g3 = t5 %>% 
  ggplot(mapping = aes(x = index, y = varx, color = label)) + 
  geom_line() + 
  my_theme
g3
```

```{r}
g4 = t5 %>% 
  ggplot(mapping = aes(x = index, y = vary, color = label)) + 
  geom_line() + 
  my_theme
g4
```












